### GET ADMIN
GET http://localhost:5000/api/admins
Accept: application/json

### login
POST http://localhost:5000/api/admins/login
Content-Type: application/json

{
  "email": "vitaliy.p@halo-lab.team",
  "password": "111111"
}

### login no existed user
POST http://localhost:5000/api/admins/login
Content-Type: application/json

{
  "email": "ss@gmail.com",
  "password": "2222"
}

### register
POST http://localhost:5000/api/admins/new
content-type: application/json

{
  "email": "11dcddss@gmail.com",
  "password": "",
  "name": "Vitaliy"
}

### ME
GET http://localhost:5000/api/admins/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTA5MTUxLCJleHAiOjE2NDIzNjgzNTF9.gUQSN7-Mydz6DGivtMYiwX3qqUKYgnTMuaqRiTgMefs

### GET project
GET http://localhost:5000/api/projects/84b728ee-b913-403b-87dd-6d38da78898a
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTA5MTUxLCJleHAiOjE2NDIzNjgzNTF9.gUQSN7-Mydz6DGivtMYiwX3qqUKYgnTMuaqRiTgMefs

/// ->
### create project
POST http://localhost:5000/api/projects
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTA5MTUxLCJleHAiOjE2NDIzNjgzNTF9.gUQSN7-Mydz6DGivtMYiwX3qqUKYgnTMuaqRiTgMefs

{
  "projectName": "7.11(2)"
}

### DELETE project
DELETE http://localhost:5000/api/projects/8358a0f1-a071-40d9-bb04-6c1f4153fbc7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTA5MTUxLCJleHAiOjE2NDIzNjgzNTF9.gUQSN7-Mydz6DGivtMYiwX3qqUKYgnTMuaqRiTgMefs

### PUT project
PUT http://localhost:5000/api/projects/8021a115-e619-42c5-a3e2-da7ae44ff1eb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTA5MTUxLCJleHAiOjE2NDIzNjgzNTF9.gUQSN7-Mydz6DGivtMYiwX3qqUKYgnTMuaqRiTgMefs

{
  "projectname": "0update name"
}

### GET tasks
GET http://localhost:5000/api/project/tasks/063a2c71-ce72-483f-a545-4a488b757d32
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTA5MTUxLCJleHAiOjE2NDIzNjgzNTF9.gUQSN7-Mydz6DGivtMYiwX3qqUKYgnTMuaqRiTgMefs

### create task
POST http://localhost:5000/api/tasks
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTA5MTUxLCJleHAiOjE2NDIzNjgzNTF9.gUQSN7-Mydz6DGivtMYiwX3qqUKYgnTMuaqRiTgMefs

{
  "task_name": "5 task",
  "project_id": "803903df-bf76-41a9-aa7a-0c4756279975"
}

### DELETE task
DELETE http://localhost:5000/api/task/5fe122cb-c3cf-4b79-ac31-4b8c145f0342
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTg1NzAyLCJleHAiOjE2NDI0NDQ5MDJ9.Gq_XznHVsMzNW9EA2Qjb5dQx0tjpvWGwv6xSEGO3dyU

### PUT task
PUT http://localhost:5000/api/task/41cb3277-3943-45be-afa2-7e1a96e92280
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiODRiNzI4ZWUtYjkxMy00MDNiLTg3ZGQtNmQzOGRhNzg4OThhIiwiZW1haWwiOiJ2aXRhbGl5LnBAaGFsby1sYWIudGVhbSIsInBhc3N3b3JkIjoiMTExMTExIiwibmFtZSI6ImQifSwiaWF0IjoxNjQyMTg1NzAyLCJleHAiOjE2NDI0NDQ5MDJ9.Gq_XznHVsMzNW9EA2Qjb5dQx0tjpvWGwv6xSEGO3dyU

{
  "task_name": "0update name",
  "create_date": "",
  "time": "30",
  "project_id": "803903df-bf76-41a9-aa7a-0c4756279975",
  "user_id": "84b728ee-b913-403b-87dd-6d38da78898a"
}
